### ISSUE TITLE
Incorrect loss in Tic-tac-toe Plus

### ISSUE THREAD

**Issue by jasonharrison** [freeboardgames/FreeBoardGames.org#424]
While playing against the AI (I am red X)

![Screenshot_20200112-042538](https://user-images.githubusercontent.com/304383/72216825-2673a880-34f4-11ea-9c7c-dedc6b0d7ad4.png)

**Comment by gk-patel** [comment]
I also experienced the same bug, i tried to fix it by returning the winner back as the output of isVictory(). Perviously it was returning true/false back, so if the Plus would come from the opponent, and it you would win because of that, the opponent was declared the winner. I fixed this in the branch ttt_bug.
