### ISSUE TITLE
stop at DropClientPage when run prod 

### ISSUE THREAD

**Issue by peacetrue** [freeboardgames/FreeBoardGames.org#530]
When i run ``npm run prod``, I always get stuck at **DropClientPage**
![image](https://user-images.githubusercontent.com/38878763/80925590-9c618f80-8dc3-11ea-99eb-779e621bd531.png)

``cat /etc/redhat-release``:  **CentOS Linux release 7.6.1810 (Core)**
``npm -v``: **6.14.4**

When I run on mac, there is no problem.  Can you help me?

**Comment by jasonharrison** [comment]
Hi, we use the yarn package manager (not npm).  Try running `rm -rf node_modules/ package-lock.json; yarn install`

Then try `yarn run prod` 

If this fails, can you tell us what version of Node you're using?  `node -v`

**Comment by peacetrue** [comment]
@jasonharrison 
I did what you said.

![image](https://user-images.githubusercontent.com/38878763/80931100-51a73e00-8dea-11ea-98c1-d0252eca8904.png)

![image](https://user-images.githubusercontent.com/38878763/80931104-59ff7900-8dea-11ea-904c-9524c781b6e6.png)

**Comment by jasonharrison** [comment]
Hi, it looks like you did `rm -rf node_modules/package-lock.json`, which is actually very different.  There should be a space because we want to remove both the node_modules directory **and** ./package-lock.json.

Try: `rm -rf node_modules/ package-lock.json; yarn install`

By the way, if you would prefer, we might be able to figure this out on Discord.  Here is our server: https://discord.gg/AaE6n3n .

**Comment by peacetrue** [comment]
@jasonharrison

**Comment by peacetrue** [comment]
@jasonharrison 
![image](https://user-images.githubusercontent.com/38878763/80932052-24f62500-8df0-11ea-85a5-6bd7b4ac5360.png)

**Comment by peacetrue** [comment]
I tried many times and finally succeeded.

![image](https://user-images.githubusercontent.com/38878763/80943088-f93b6500-8e18-11ea-922b-c2cdb6c1542f.png)

**Comment by peacetrue** [comment]
@jasonharrison  for some reason, I cannot access [https://discord.gg/AaE6n3n](https://discord.gg/AaE6n3n)
