### ISSUE TITLE
[Zoo Parade] Bugs

### ISSUE THREAD

**Issue by Spooky-0** [freeboardgames/FreeBoardGames.org#614]
1) ~~Values should be 1-5 not  0-4~~ **Resolved in #619** 
2) When a player recieves a nr/clr hint, all boxes should be black except for the truth. E.g. You know you have a 2, then you should see [ ] [2] [ ] [ ] [ ]... currently you see [1] [2] [3] [4] [5]
3) Colors of the little squares need to be same as the cards ( I added a text file to the media folder with the cards. There is a link to the color pallet)
4) As alraedy known, the little boxes overlap the cards.

**Comment by jasonharrison** [comment]
Would you please split these up into individual GitHub issues? This will be easier to track.

**Comment by DanielSherlock** [comment]
1) Further resolved by #623

**Comment by DanielSherlock** [comment]
2) Will be sorted by #624, once the corresponding tests are written.

**Comment by DanielSherlock** [comment]
3. I think we just need to change the `colors` array in [web/src/games/zooparade/components/bhinticon.tsx](https://github.com/freeboardgames/FreeBoardGames.org/blob/master/web/src/games/zooparade/components/bhinticon.tsx)?

**Comment by DanielSherlock** [comment]
4) Wait, was that an issue? I thought that was the way you lot had decided on to make it looked less cluttered. I kinda liked it. Where do you want them to be instead?

**Comment by Spooky-0** [comment]
> 4) Wait, was that an issue? I thought that was the way you lot had decided on to make it looked less cluttered. I kinda liked it. Where do you want them to be instead?

Yes. But then I redesigned the cards and now they have a different ratio. They are a bit shorter. And consequently some hintsquares are below the card.

**Comment by flamecoals** [comment]
I think all the 4 issues are resolved now? But I found some more playing with friends today:

![Screenshot_20200916-000708](https://user-images.githubusercontent.com/1034631/93287989-42c99280-f7b1-11ea-9051-474e06baec59.png)
- The deck went to -3 instead of (game over?)

- (mobile) The top deck being built didn't fit on my phone, so one card wrapped in a new line. Even though the players decks with the same number of cards did fit.

- (mobile) There was no padding on the top of the page, so the FBG bar was hiding half the cards of the top deck

- (mobile) there was no padding on the bottom of the page, so the android menu was hiding half the buttons

**Comment by DanielSherlock** [comment]
> (mobile) There was no padding on the top of the page, so the FBG bar was hiding half the cards of the top deck

> (mobile) there was no padding on the bottom of the page, so the android menu was hiding half the buttons

Was something done about this? I ask because last time I played a game I had a different bug with the padding (though one of my friends, on a different OS&browser, didn't) which made the log unviewable, and wondered whether it was introduced recently. There were also other, even more important bugs I want to deal with soon, but I feel like the proper thing to do is to open a new issue for each bug?

If those-in-charge are happy for me to try and tidy up all the Zoo Parade issues, that could be a sensible first step?

**Comment by flamecoals** [comment]
@DanielSherlock yes, I think I sent a PR to fix these bugs you mention.

Tidying up the issues would be very welcomed !

**Comment by flamecoals** [comment]
@DanielSherlock you should have access on github to manage issues already :)

**Comment by DanielSherlock** [comment]
Hello all,

It's been a while, but here's what I think the state of all the bugs in Zoo Parade is:

+ Of the original 4 bugs mentioned in this issue:
  1. Was solved by #620 and #623
  2. Feature was added in #624
  3. @vdfdev thinks this is solved: looks like this was fixed with #630
  4. As above: it looks like this was patched in #617
+ Of the issues identified by @vdfdev:
  - The first one has been fixed in #630 by showing the "empty" card, but a related bug remains - see the new issue #865.
  - The second is still around in at least some form: _(At some screen sizes)_ the cards in the hands squish up and slightly overflow the screen. The layout piles at the top still wrap onto a new line. _I think all this might be because, when the size of the cards was changed, it wasn't changed everywhere (maybe?) so this might still be fixable by going through the code and making sure all the sizes are consistent. If not, it'll need a deeper look at the CSS. For now, as it seems to happen very very rarely, and doesn't affect the game, I'm planning on ignoring it until more fundamental layout problems (e.g. #868) have been addressed and I know what's going on._
  - The others I haven't been able to test, but as @vdfdev says, should be resolved in #630, specifically [this commit] (at least, it's seems like that's what those changes are doing).
+ The issue I mentioned, and the others I alluded to are similarly unresolved and now also have their own issues: see #866, #867, and #868.
+ For completeness, I'll also mention that the important _(if we want to keep to the rules of Hanabi)_ missing feature in #615 remains unimplemented.

As I've now accounted for all the various known bugs and separately replaced those that are still a problem, I'm now going to close this issue.

[this commit]: https://github.com/freeboardgames/FreeBoardGames.org/commit/fe96ae5691e6f6f91c2f87890f66e6076139c257

**Comment by vdfdev** [comment]
Thanks for reviewing and organizing this!
