### ISSUE TITLE
[Windows Dev] Bgio server isn't starting if using the CLI

### ISSUE THREAD

**Issue by vdfdev** [freeboardgames/FreeBoardGames.org#678]
Developers on windows get  "Failed to start a Match" when trying to start a Match on windows.

Seems to be an issue with the CLI, unknown reason yet. The current workaround is to do  "yarn run gen:games && yarn run dev:internal" on the root folder to bypass CLI.

**Comment by flamecoals** [comment]
I tried on my windows machine, and the issue seems to be with "start-server-and-test" probably not liking the env created by shelljs....

I want to in the future manage the instantiation and running of the 3 servers on the CLI itself, so we can present a better UI for the user. This would hopefully solve this issue.

**Comment by sefgit** [comment]
What are the different ports number for ?
3000: web server
3001: proxy ?
8001: bgio ?

Tried to find them in documentation but without luck.

**Comment by vdfdev** [comment]
Fixed by #955
